import { MASTER_PASSWORD } from "./password";

/**
 * This interface represents the full set of values that represent a
 * proof of knowledge of the master password.
 */
export interface FullProof {
  // TODO: fill this in
  valid: boolean;
}

/**
 * Given a string password, generates a proof of knowledge of that password.
 */
export async function generateProofOfPasswordKnowledge(
  password: string
): Promise<FullProof> {
  return {
    valid: password === MASTER_PASSWORD,
  };
}

/**
 * Given a proof generated by {@link generateProofOfPasswordKnowledge}, verifies it
 * represents knowledge of the master password.
 */
export async function verifyPasswordKnowledge(
  fullProof: FullProof
): Promise<boolean> {
  return fullProof.valid;
}
